---
agimus_controller_node:
  ros__parameters:
    rate: 100.0
    publish_debug_data: false
    constant_delay: false
    free_flyer: false
    collision_as_capsule: true
    self_collision: true
    robot_attachment_frame: robot_attachment_link
    ocp:
      dt: 0.01
      horizon_size: 19
      armature: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]
      max_qp_iter: 100
      max_iter: 10
      use_constraints: true
      activate_callback: false
      increasing_weights:
        max: 100.0
        percent: 0.9
        time_reach_percent: 6
      effector_frame_name: fer_link8
    collision_pairs_names: [cp_1]
    cp_1:
      first: fer_link7_sc_capsule_0
      second: fer_link3_sc_capsule_0

